apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-data-pv
  labels:
    type: mssql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mssql
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mssql/data
    server: #servername
