apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-backup-pv
  labels:
    type: mssql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mssqlbackup
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mssql/backup
    server: #servername
