---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data-claim
  labels:
    app: mssql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mssql
  resources:
    requests:
      storage: 20Gi
