---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-backup-claim
  labels:
    app: mssql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mssqlbackup
  resources:
    requests:
      storage: 20Gi
