apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-storage-pv
  labels:
    type: mssql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mssqlstorage
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mssql/storage
    server: #servername
